package admin

const simplePanelTemplate = `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Ryubot Admin</title><style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;background:#090b10;color:#edf0f7}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1080px;margin:auto;padding:28px}.card{background:#121722;border:1px solid #273044;border-radius:16px;padding:22px;margin-bottom:18px}h1,h2{margin-top:0}label{display:grid;gap:7px;color:#b9c2d3;font-size:14px}input{width:100%;padding:11px;border:1px solid #354159;border-radius:9px;background:#0b0f17;color:#fff}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(205px,1fr));gap:14px}.row{display:flex;gap:10px;align-items:center;justify-content:space-between}.badge{padding:6px 10px;border-radius:99px;background:#22304b;color:#b9d1ff}button{border:0;border-radius:9px;padding:11px 16px;background:#4f7cff;color:white;font-weight:700;cursor:pointer}.error{background:#51252a;padding:12px;border-radius:9px}.ok{background:#174b39;padding:12px;border-radius:9px}.login{max-width:400px;margin:10vh auto}.muted{color:#8994a8;font-size:13px}</style></head><body><main class="wrap">
{{if .Login}}<section class="card login"><h1>Ryubot Admin</h1>{{if .Error}}<p class="error">{{.Error}}</p>{{end}}<form method="post" action="/admin/login"><label>Username<input name="username" autocomplete="username" required></label><br><label>Password<input name="password" type="password" autocomplete="current-password" required></label><br><button>Masuk</button></form></section>
{{else}}<div class="row"><div><h1>Aturan Bisnis</h1><p class="muted">Login sebagai {{.Admin.Username}}</p></div><form method="post" action="/admin/logout"><input type="hidden" name="csrf" value="{{.Admin.CSRF}}"><button>Keluar</button></form></div>{{if .Error}}<p class="error">{{.Error}}</p>{{end}}{{if .Saved}}<p class="ok">Aturan langsung disimpan dan aktif.</p>{{end}}
<form method="post" action="/admin/rules/save"><input type="hidden" name="csrf" value="{{.Admin.CSRF}}">
<section class="card"><div class="row"><h2>Pembagian Profit</h2><span class="badge">{{.Rules.Status}} v{{.Rules.Version}}</span></div><div class="grid"><label>User %<input name="user_percent" value="{{.Rules.UserPercent}}" required></label><label>Akun penampung %<input name="holding_percent" value="{{.Rules.HoldingPercent}}" required></label><label>kangden69 %<input name="kangden_percent" value="{{.Rules.KangdenPercent}}" required></label><label>Username bebas fee<input name="fee_exempt_username" value="{{.Rules.FeeExemptUsername}}" required></label></div></section>
<section class="card"><h2>Referral</h2><div class="grid"><label>Level 1 %<input name="referral_1" value="{{.Rules.Referral1}}" required></label><label>Level 2 %<input name="referral_2" value="{{.Rules.Referral2}}" required></label><label>Level 3 %<input name="referral_3" value="{{.Rules.Referral3}}" required></label></div></section>
<section class="card"><h2>Subscription</h2><div class="grid"><label>Harga TRX<input name="subscription_price" value="{{.Rules.SubscriptionPrice}}" required></label><label>Upline TRX<input name="upline_reward" value="{{.Rules.UplineReward}}" required></label><label>Management TRX<input name="management_amount" value="{{.Rules.ManagementAmount}}" required></label><label>Trial hari<input name="trial_days" type="number" value="{{.Rules.TrialDays}}" required></label></div></section>
<section class="card"><h2>Owner</h2><div class="grid"><label>Kang Nana %<input name="owner_nana" value="{{.Rules.OwnerNana}}" required></label><label>Kang Deni %<input name="owner_deni" value="{{.Rules.OwnerDeni}}" required></label><label>Pak Arya %<input name="owner_arya" value="{{.Rules.OwnerArya}}" required></label><label>Operasional %<input name="operational" value="{{.Rules.Operational}}" required></label><label>Zona waktu<input name="timezone" value="{{.Rules.Timezone}}" required></label><label>Cutoff 1<input name="cutoff_1" type="time" value="{{.Rules.Cutoff1}}" required></label><label>Cutoff 2<input name="cutoff_2" type="time" value="{{.Rules.Cutoff2}}" required></label></div></section>
<section class="card"><button>Simpan dan Terapkan</button><p class="muted">Perubahan langsung menjadi versi aktif. Versi sebelumnya tetap tersimpan sebagai histori.</p></section></form>{{end}}</main></body></html>`
